version: "2.4"

services:
  play:
    build: .
    volumes:
      - .:/node/app
      - /node/app/node_modules
    networks:
      - backend
    ports:
      - 8000:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=Egypt
      - DATABASE_HOST=db
      - JWTKEY=secret

  db:
    build: ./data/database
    volumes:
      - ./data/database/files:/var/lib/mysql
    networks:
      - backend
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
    environment:
      - TZ=Egypt
      - DATABASE_HOST=db
      - MYSQL_ROOT_PASSWORD=playpassword

networks:
  backend:
